import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Monument = localFont({
  src: "./fonts/Monument-B.ttf",
  variable: "--Monument",
  weight:"100 700"
});

const Gilroy_M = localFont({
  src:"fonts/Gilroy-M.ttf",
  variable:"--Gilroy-M"
})
const Gilroy_R = localFont({
  src:"fonts/Gilroy-R.ttf",
  variable:"--Gilroy-R"
})
export const metadata: Metadata = {
  title: "Showcase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Monument.variable} ${Gilroy_M.variable} ${Gilroy_R.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
